config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  get '/orders', to: 'orders#index'
  get '/orders/new', to: 'orders#new'
  get '/orders/show', to: 'orders#show'
  post '/orders', to: 'orders#create'
  get '/admin', to: 'admin#index'
  get '/admin/newpriceplan', to: 'admin#newpriceplan', as: 'priceplans'
  post '/admin/newpriceplan', to: 'admin#create', as: 'priceplans_new'
  delete 'admin/newpriceplan', to: 'admin#destroy'
  get '/menus', to: 'menus#index'
  get '/menus/new', to: 'menus#new'
  post '/menus', to: 'menus#create'
  delete '/menus', to: 'menus#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itemlist.rb
class Itemlist < ApplicationRecord
  belongs_to :order
end

app/models/menu.rb
class Menu < ApplicationRecord

  mount_uploader :img_location, MenuImageUploader

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :itemlist
end

app/models/priceplan.rb
class Priceplan < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @priceplans = Priceplan.all
  end

  def newpriceplan
    @priceplan = Priceplan.new
  end
  
  def create
    @priceplan = Priceplan.new(priceplan_params)
    if @priceplan.save
      redirect_to admin_url
    else

    end
  end

  def destroy
    @priceplan = Priceplan.find(params[:id]).destroy
    redirect_to admin_url
  end
  
  
  private
  def priceplan_params
    params.require(:priceplan).permit(:no_of_people, :no_of_dishes, :price, :add_item_cost)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      render :new
    end
  end

  def index
    @menus = Menu.all
  end
  
  def destroy
    @menu = Menu.find(params[:id]).destroy
    redirect_to menus_path
  end
  

  private
  def menu_params
    params.require(:menu).permit(:item, :description, :img_location)
  end
  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index

  end

  # Show order for each user
  def show
    @orders = Order.all
  end
  
  
  def new 
    @order = Order.new
    @menus = Menu.all
    @priceplan = Priceplan.all
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to orders_url
    else
      render :new
    end
  end

  private
  def order_params
    params.require(:order).permit(:custname, :contactnumber, :custaddress, :email, :deliveryDate)
  end
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def getItemList(orderid)
    itemlist = Itemlist.where(order_id: orderid).pluck(:itemname)
    return itemlist
  end
  

end

app/views/admin/index.html.erb
<center> 
<h1>This is admin page</h1> 
<br><%= link_to 'Show all Orders', orders_show_path %> 
<br><%= link_to 'Show Menu', menus_path %>
<br><%= link_to 'New Food Item', menus_new_path %>


        <div class="panel panel-default">
          <h1>Current Available Price Plan</h1>
            <div class="panel-body">
                <% @priceplans.each do |y|%>
                    <%= y.no_of_people %> Pax | 
                    <%= y.no_of_dishes %> Dishes @
                    <%= y.price %> | Each Additional Item: $
                    <%= y.add_item_cost %>
                    <%= link_to 'Delete', priceplans_path(id: y.id), method: :delete, data: { confirm: "Are you sure?" } %><br>
                <% end %>
            </div> <!-- end of panel body -->
            
            <%= link_to 'New Price Plan', priceplans_new_path %>
        </div><!-- end of panel panel default -->


</center>

app/views/admin/newpriceplan.html.erb
<%= form_for @priceplan do |f| %>

    <div class="ui fluid form">
        <div class="inline fields">
            <div class="field">
                <label for="no_of_people"> <%= f.label :no_of_people %></label>
                <%= f.text_field :no_of_people %> 
            </div>
            <div class="field">
                <label for="no_of_dishes"><%= f.label :no_of_dishes %></label>
                <%= f.text_field :no_of_dishes %>
            </div>

            <div class="field">
                <label for="price"><%= f.label :price %></label>
                <%= f.text_field :price %>
            </div>
            <div class="field">
                
                <%= f.label :add_item_cost %>
                <%= f.text_field :add_item_cost %>
        
            </div>
            <br/>

        </div>

        <br>
  <%= f.submit %>
  <%= link_to 'Back to index', root_path %>
<% end %>

app/views/layouts/_nav.html.erb
<div class="ui menu">
    <div class="teal item">
        <%= link_to 'Admin', admin_path %>
    </div>
    <div class="teal item">
        <%= link_to 'Orders', orders_path %>
    </div>
     <div class="teal item">
        <%= link_to 'Back to Index!', root_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CateringApp</title>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.4.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.css"/>
    <link href="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.css"
          rel="stylesheet" type="text/css"/>
    <script src="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.js"></script>



    <style>
        .ui.card {
            height: 420px;
        }

        }
    </style>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
Current Menu
<div class="panel panel-default" id="menupanel">
    <% @menus.each do |x| %>
    <div class="panel panel-default" id="menucard">
        
        <div id="menuimage"><%= image_tag x.img_location.url %></div>

        <div class="content">
            <div class="header"><%= x.item %>
            </div>
            <div class="description"><%= x.description %>.
            </div>
        </div>
        <div class="extra content"><!-- start of extra content -->
            <div class="ui labeled icon menu">
                <div class="ui left floated compact segment">
                    <%= check_box_tag(x.itemtag) %>
                    <label>Active</label>
                </div>
                <%= link_to 'Delete', menus_url(id: x.id), method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
            
        </div><!-- end of extra content -->
    </div>
    <% end %>
</div>

app/views/menus/new.html.erb
<%= form_for @menu do |f| %>

    <div class="ui fluid form">
        <div class="inline fields">
            <div class="field">
                <label for="items"> <%= f.label :item %></label>
                <%= f.text_field :item %> 
            </div>
            <div class="field">
                <label for="last_name"><%= f.label :itemtag %></label>
                <%= f.text_field :itemtag %>
            </div>

            <div class="field">
                <label for="last_name"><%= f.label :description %></label>
                <%= f.text_field :description %>
            </div>
            <div class="field">
                
                <%= f.label :img_location%>
                <%= f.file_field :img_location%>
        
            </div>
            <br/>

        </div>

        <br>
  <%= f.submit %>
  <%= link_to 'Back to index', root_path %>
    </div>


<% end %>

app/views/orders/index.html.erb
<div class="ui container">
<h1>This is the orders index page</h1>

    <button class="ui basic red button"><%= link_to "New Order!", orders_new_path %> </button>
    <button class="ui basic red button"><%= link_to "Show Order!", orders_show_path %> </button>
     <button class="ui basic red button"><%= link_to 'Back to Index!', root_path %> </button>
</div>

app/views/orders/new.html.erb
<%# Select price plan%>


<br>
<div class="ui container">
    <%= form_for @order do |f| %>
    <h2>Price plan</h2>
        <div class="panel panel-default">

            <div class="panel-body">
                <% @priceplan.each do |y|%>
                    <%= radio_button_tag(:id, y.id) %>
                    <%= y.no_of_people %> Pax | 
                    <%= y.no_of_dishes %> Dishes @
                    <%= y.price %> | Each Additional Item: $
                    <%= y.add_item_cost %><br>
                <% end %>
            </div> <!-- end of panel body -->
        </div><!-- end of panel panel default -->

    <h2>Current Menu</h2>
    <br>
    <div class="panel panel-default" id="menupanel"><!-- Start of ui grid-->
        <!-- Start of ui grid row -->
            
              <% @menus.each do |x| %>
                <div class="panel panel-default" id="menucard">
                    <div id="menuimage"><%= image_tag x.img_location.url %></div>

                    <div class="content">
                        <div class="header"><%= x.item %></div>
                        <div class="description"><%= x.description %>.
                        </div>
                    </div>
                    <div class="extra content">
                        <div class="ui labeled icon menu">
                            <div class="ui left floated compact segment">
                                
                                    <%= check_box_tag(x.itemtag) %>
                                    <label>Active</label>
                                
                            </div>
                        </div>
                    </div><!-- end of extra content -->
                </div><!-- end of ui card -->
            <!-- end of row-->
             <% end %>
        <!-- end of ui grid row -->
    </div><!-- End of ui grid -->
             
             <p><p>



    <div class="ui fluid form"><!-- Start of ui fluid form -->
        <div class="inline fields">
            <div class="field">
                <label for="first_name"> <%= f.label :custname %></label>
                <%= f.text_field :custname %> 
            </div>
            <div class="field">
                <label for="last_name"><%= f.label :contactnumber %></label>
                <%= f.text_field :contactnumber %>
            </div>

            <div class="field">
                <label for="last_name"><%= f.label :email %></label>
                <%= f.text_field :email %>
            </div>
            <div class="field">
                
                      <%= f.label :deliveryDate%>
                      <%= f.date_field :deliveryDate%>
                
            </div>
            <br/>

        </div> <!-- End of inline fields -->


        <div class="field">
            <label for="address">Customer Address</label>
            <%= f.text_area :custaddress %>
        </div>

        <br>
  
        <div class="ui left action input">
            <button class="ui labeled icon button">
                <i class="cart icon"></i>
                <%= f.submit %>
            </button>
            <input type="text" value="$70.00" readonly>
        </div>
    </div><!-- End of ui form -->


<% end %>

</div><!-- end of ui containter -->

app/views/orders/show.html.erb
<br>
<% @orders.each do |order| %>
  <br>ID: <%= order.id %>
  <br>Customer Name: <%= order.custname %>
  <br>Customer Email: <%= order.email %>
  <br>Contact Number: <%= order.contactnumber %>
  <br>Customer's Address: <%= order.custaddress %>
  <br>Price Plan: <%= order.price_plan %>
  <br>Delivery Date: <%= order.deliveryDate %>
  <br>No of Items Selected: <%= order.no_of_items_sel %>
  <br>Itemlist: <% @itemlist = getItemList(order.id) %>
  <% (0..@itemlist.length-1).each do |index| %>
    <br><%= index+1 %>. <%= @itemlist[index] %>
  <% end %>
  <br>Final Price: <%= order.finalprice %>
<% end %>

app/views/static_pages/index.html.erb
<div class="ui container">
<h1>Welcome to the Catering App!</h1>
<button class="ui basic red button"><%= link_to 'View Menu!', menus_path %> </button> 
<button class="ui basic red button"><%= link_to 'New Order!', orders_new_path %> </button> 
<button class="ui basic red button"><%= link_to 'View Order!', orders_show_path %> </button> 
</div>